# Generated by Django 3.0.5 on 2020-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEW',
            fields=[
                ('text', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
